# Generated by Django 4.2 on 2024-10-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_cours"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cours",
        ),
    ]
