# Generated by Django 5.1.1 on 2024-10-16 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_about_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="progress",
        ),
    ]
