# Generated by Django 5.1.1 on 2024-10-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_customuser_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="about",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="specialite",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
