# Generated by Django 5.1.1 on 2024-10-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_course_userloginattempt_useralert_and_more"),
        ("gestionCours", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursparticiperparuser",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestionCours.course"
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
