# Generated by Django 4.2 on 2024-10-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_coursparticiperparuser_course_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursParticiperParUser',
        ),
    ]
