# Generated by Django 4.2 on 2024-10-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voice",
            fields=[
                ("AudioMp3", models.FileField(upload_to="audio/")),
                ("user_id", models.IntegerField()),
                ("AudioText", models.TextField()),
                ("AudioLangue", models.CharField(default="anglais", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SortieVoice",
            fields=[
                ("AudioSortieMp3", models.FileField(upload_to="audio/sortie/")),
                ("AudioSortieText", models.TextField()),
                ("AudioLangue", models.CharField(max_length=100)),
                (
                    "voice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionLangue.voice",
                    ),
                ),
            ],
        ),
    ]
