# Generated by Django 5.1.1 on 2024-10-30 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLangue', '0002_inputtranslator_outputtranslator_delete_sortievoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtranslator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outputtranslator',
            name='input_translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionLangue.inputtranslator'),
        ),
    ]
