# Generated by Django 5.1.1 on 2024-10-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLangue', '0003_alter_inputtranslator_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtranslator',
            name='input_voice',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='gestionLangue/input_voice/'),
        ),
        migrations.AlterField(
            model_name='outputtranslator',
            name='output_voice',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='gestionLangue/output_voice/'),
        ),
    ]
