# Generated by Django 5.1.1 on 2024-10-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLangue', '0004_alter_inputtranslator_input_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtranslator',
            name='input_voice',
            field=models.FileField(blank=True, null=True, upload_to='gestionLangue/input_voice/'),
        ),
        migrations.AlterField(
            model_name='outputtranslator',
            name='output_voice',
            field=models.FileField(blank=True, null=True, upload_to='gestionLangue/output_voice/'),
        ),
    ]
